# -*- coding: utf-8 -*-
"""GreenAI_unet_weighted_GAI_3_4_22_working.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HYx4QgOs4YZeRBCIllsHg5Xu3lWYXjp5
"""

# from google.colab import drive
# drive.mount('/content/drive')

# !pip3 install patchify
# !pip3 install tensorflow==2.2
# !pip3 install keras==2.3.1
# !pip3 install -U segmentation-models

# # https://youtu.be/jvZm8REF2KY
# """
# Explanation of using RGB masks: https://youtu.be/sGAwx4GMe4E
# """


# import os
# import cv2
import numpy as np
import cv2

from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = MinMaxScaler()



# test_img_root_directory='G:\My Drive\ProjectGreenAI\Data\\randomImagesTamarind\\images/'

#Read images from repsective 'images' subdirectory
#As all images are of ddifferent sizes resize all to a fixed size
# But, using following code it is possible to crop into a fixed size

filename= 'randomImage2.tiff'
filename= 'Capture.jpg'


def getPrediction(img, my_model, toggle: bool = False) -> float:

    '''this predicts the GAI of the inserted image and returns a number. 
    
    @param img: img to predict on
    @param model: The segmentation model
    @param toggle: if set to true the image and predicted image will be saved to 'area_of_interest.png' and 'pred.png'
    '''
    
    SIZE = 256

    img = cv2.resize(img, (SIZE,SIZE))

    if toggle:
        cv2.imwrite('area_of_interest.png', img)
    img1 = np.zeros(img.shape, dtype=np.float64)               
    #Use minmaxscaler instead of just dividing by 255. 
    
    for channel in range(3):
        img1[:, :, channel] = scaler.fit_transform(img[:, :, channel])
    # img = scaler.fit_transform(img)
    img = np.array(img1)
    
    img = np.expand_dims(img, axis=0)  #Get it tready as input to the network  
    
    pred = my_model.predict(img) #Predict
    y_pred_argmax=np.argmax(pred, axis=3)


#######################################################################
    i=0
    predicted_img = y_pred_argmax[0]
    # print('Image number {}'.format(i+1))
 
 # ############### GAI of predicted output #####################################################

    pred_whole_area = np.sum(predicted_img > 0)
    pred_asphalt= np.sum(predicted_img == 1)
    pred_building = np.sum(predicted_img == 2)
    pred_bush = np.sum(predicted_img == 3)
    # pred_cultivLand = np.sum(predicted_img == 4)
    # print('Predcited Cultiv Land area : ', pred_cultivLand)
    pred_grass = np.sum(predicted_img == 4)
    pred_newTree = np.sum(predicted_img == 5)
    pred_oldTree = np.sum(predicted_img == 6)
    # pred_parking = np.sum(predicted_img== 8)
    # print('predicted parking : ', pred_parking)
    pred_social = np.sum(predicted_img== 7)

   
    # pred_GAI = ((pred_bush*0.85)+(pred_cultivLand *1.5)+(pred_grass*1.5)+(pred_newTree*1.63)+(pred_oldTree*1.55)+(pred_social*1.2))/(org_whole_area-1000)
  
    pred_GYF = ((pred_bush*0.85)+(pred_grass*1.5)+(pred_newTree*1.63)+(pred_oldTree*1.55)+(pred_social*1.2))/(pred_whole_area-200)
    print('Image No.:{}, Predicted GYF:{:.2f} '.format(i+1,pred_GYF) )
    
    # return pred_GYF

# test_prediction= getPrediction(filename)
    
    # print('pred_truth whole area : ', pred_whole_area)
    # print('predicted asphalt area : ', pred_asphalt)
    # print('predictedbuilding area : ', pred_building )
    # print('predicted Bush area : ', pred_bush)
    # print('predicted Grass area : ', pred_grass)
    # print('predicted newTree area : ', pred_newTree)
    # print('predicted oldTree area : ', pred_oldTree)
    # print('predicted social area : ', pred_social)
    
    
    # plt.figure(figsize=(12, 8))
    # plt.subplot(231)
    # plt.title('Testing Image')
    # plt.imshow(test_img)
    # plt.subplot(232)
    # # plt.title('Testing Label')
    # # plt.imshow(ground_truth)
    # # plt.subplot(233)
    # plt.title('Predicted GYF = % 1.2f' % pred_GYF)
    # plt.imshow(predicted_img,cmap='jet')
    # plt.show()

   

    ##### Plot with legends #######
    data = np.random.randint(0, 9, (5,5))
    # values = np.unique(labels)
    values=[0,1,2,3,4,5,6,7]
    legends = {0:'outside',1:'Asphalt',2:'Building',3:'Bush',4:'Grass', 5:'newTree',6:'oldTree',7:'socialArea'}
    
    import matplotlib.patches as mpatches
    import matplotlib.pyplot as plt
    im = plt.imshow(predicted_img, interpolation='none')
    # get the colors of the values, according to the 
    # colormap used by imshow

    colors = [ im.cmap(im.norm(value)) for value in values]
    patches = [mpatches.Patch(color=colors[i], label=legends[i] ) for i in range(len(values)) ]
    plt.title('Predicted GYF = % 1.2f' % pred_GYF)
    plt.legend(handles=patches, bbox_to_anchor=(1.05, 1), loc=2, borderaxespad=0. )
    #plt.grid(True)

    if toggle:
        plt.savefig('pred.png')

    # plt.show()
    return pred_GYF

# from keras.models import load_model
# model_path = r'green_ai\web\model\unet_bata.hdf5'
# model = load_model(model_path, compile=False)
# img = cv2.imread('C:/crop_orto/area_of_interest.png')
# getPrediction(img, model) 